---
abstract: 'Sane database change management'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Capture::Tiny: '0.12'
  Carp: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  FindBin: '0'
  Module::Build: '0.35'
  Test::Deep: '0'
  Test::Dir: '0'
  Test::Exception: '0'
  Test::File: '0'
  Test::File::Contents: '0.20'
  Test::MockModule: '0.05'
  Test::More: '0.94'
  Test::NoWarnings: '0.083'
  lib: '0'
configure_requires:
  Module::Build: '0.35'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Sqitch
no_index:
  directory:
    - priv
recommends:
  Class::XSAccessor: '1.18'
  Pod::Simple: '1.41'
  Type::Tiny::XS: '0.010'
requires:
  Clone: '0'
  Config::GitLike: '1.11'
  DBI: '0'
  DateTime: '0'
  Devel::StackTrace: '1.30'
  Digest::SHA: '0'
  Encode: '0'
  Encode::Locale: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  Hash::Merge: '0'
  IO::Pager: '0'
  IPC::Run3: '0'
  IPC::System::Simple: '1.17'
  List::MoreUtils: '0'
  List::Util: '0'
  Locale::Messages: '0'
  Locale::TextDomain: '1.20'
  Moo: '1.002000'
  Moo::Role: '0'
  Moo::sification: '0'
  POSIX: '0'
  Path::Class: '0'
  PerlIO::utf8_strict: '0'
  Pod::Find: '0'
  Pod::Usage: '0'
  Scalar::Util: '0'
  StackTrace::Auto: '0'
  String::Formatter: '0'
  String::ShellQuote: '0'
  Sub::Exporter: '0'
  Sub::Exporter::Util: '0'
  Sys::Hostname: '0'
  Template::Tiny: '0.11'
  Term::ANSIColor: '2.02'
  Throwable: '0.200009'
  Time::HiRes: '0'
  Time::Local: '0'
  Try::Tiny: '0'
  Type::Library: '0.040'
  Type::Utils: '0'
  Types::Standard: '0'
  URI: '0'
  URI::db: '0.15'
  User::pwent: '0'
  constant: '0'
  if: '0'
  namespace::autoclean: '0.16'
  overload: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: http://github.com/theory/sqitch/issues/
  homepage: http://sqitch.org/
  repository: http://github.com/theory/sqitch/
version: '0.996'
